server:
  port: 9011
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://accountServer  # Load balanced URI for the account service
          predicates:
            - Path=/account/**
        - id: user-service
          uri: lb://userServer  # Load balanced URI for the account service
          predicates:
            - Path=/user/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka

